name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '16'
  main-branch-name:
    description: |
      The "main" branch of repository (the base branch which is targeted with PRs).
      Common names for this branch include main and master.
    required: false
    default: 'main'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "🤖 Release Bot"
        git config user.email "-"

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2
      with:
        main-branch-name: ${{ inputs.main-branch-name }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: ${{ inputs.node-version }}
        scope: '@rbehei-sandbox'
        # This doesn't just set the registry url, but also sets
        # the right configuration in .npmrc that reads NPM token
        # from NPM_AUTH_TOKEN environment variable.
        # It actually creates a .npmrc in a temporary folder
        # and sets the NPM_CONFIG_USERCONFIG environment variable.
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      shell: bash
      run: yarn --frozen-lockfile --no-progress --non-interactive --prefer-offline
