name: Check

on:
  pull_request:
    branches:
      - main
      - release

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Get code to get access to custom our actions
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/setup

      - name: Lint
        uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [ 14, 16 ]

    steps:
      - name: Get code to get access to custom our actions
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node_version }}
          main-branch-name: ${{ github.base_ref }}

      - name: Test
        uses: ./.github/actions/test
